# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPracticeSelenium1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_practiceSelenium1(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    self.driver.set_window_size(1470, 920)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("Admin")
    self.driver.find_element(By.NAME, "password").send_keys("admin123")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-topbar-header").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".oxd-topbar-header-title").text == "Dashboard"
    self.driver.find_element(By.CSS_SELECTOR, ".emp-leave-chart").click()
  
